name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Cache dependencies
      - name: Cache pip dependencies
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Debug cache step
      - name: Debug cache status
        run: |
          echo "Cache hit: ${{ steps.cache-pip.outputs.cache-hit }}"
          ls -la ~/.cache/pip || echo "Cache directory not found"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || { echo "pip install failed"; exit 1; }
          pip install build twine
        env:
          PIP_CONSTRAINT: requirements.txt

      # Run linting with flake8
      - name: Lint with flake8
        run: |
          flake8 . --max-line-length=120 --exclude=venv,.venv,env --show-source --statistics || { echo "flake8 failed"; exit 1; }
        continue-on-error: false

      # Run tests with unittest
      - name: Test with unittest
        run: |
          python -m unittest discover -v -s . || { echo "unittest failed"; exit 1; }

      # Build package
      - name: Build package
        run: |
          python -m build || { echo "build failed"; exit 1; }

      # Check distribution
      - name: Check distribution
        run: |
          python -m twine check dist/* || { echo "twine check failed"; exit 1; }

      # Deploy to PyPI (only on main branch push)
      - name: Publish to PyPI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload --skip-existing dist/* || { echo "PyPI upload failed"; exit 1; }
